import { Profile, Conversation, Post, Story, User, Match, Notification } from '@/types';

// ─── Avatar fiables via randomuser.me ───
const AVATAR = (id: number, gender: 'men' | 'women' = 'men') =>
  `https://randomuser.me/api/portraits/${gender}/${id}.jpg`;

export const CURRENT_USER: User = {
  id: 'user-me',
  email: 'grace@example.com',
  phone: '+243 810 000 000',
  name: 'Grace Mbuyi',
  pseudo: 'Gracia_26',
  age: 26,
  gender: 'femme',
  city: 'Kinshasa',
  profession: 'Développeuse Web',
  religion: 'Chrétienne',
  bio: 'Passionnée par la technologie et la musique. Je cherche une relation sérieuse basée sur la confiance et le respect mutuel. 🌟',
  photoUrl: AVATAR(44, 'women'),
  photoGallery: [
    AVATAR(44, 'women'),
    AVATAR(45, 'women'),
    AVATAR(46, 'women'),
    AVATAR(47, 'women'),
  ],
  verified: true,
  interests: ['Technologie', 'Musique', 'Lecture', 'Voyage', 'Cuisine'],
  preferences: {
    ageMin: 24,
    ageMax: 35,
    city: 'Kinshasa',
    gender: 'homme',
    religion: '',
  },
  createdAt: '2024-01-15T10:00:00Z',
  online: true,
  lastSeen: new Date().toISOString(),
};

export const MOCK_PROFILES: Profile[] = [
  {
    id: 'profile-1',
    userId: 'user-1',
    name: 'Patrick Lumumba',
    age: 28,
    gender: 'homme',
    city: 'Kinshasa',
    profession: 'Ingénieur Civil',
    religion: 'Chrétien',
    bio: 'Ingénieur passionné, j\'aime construire et innover. Cherche une partenaire sérieuse pour partager la vie.',
    photoUrl: AVATAR(32),
    photoGallery: [
      AVATAR(32),
      AVATAR(33),
    ],
    verified: true,
    interests: ['Architecture', 'Sport', 'Cinéma', 'Voyage'],
    distance: 3,
    online: true,
    lastSeen: new Date().toISOString(),
  },
  {
    id: 'profile-2',
    userId: 'user-2',
    name: 'Divine Kabongo',
    age: 24,
    gender: 'femme',
    city: 'Lubumbashi',
    profession: 'Médecin',
    religion: 'Chrétienne',
    bio: 'Médecin généraliste, je crois en l\'amour vrai et durable. La santé du corps et du cœur sont importantes.',
    photoUrl: AVATAR(68, 'women'),
    photoGallery: [
      AVATAR(68, 'women'),
      AVATAR(69, 'women'),
    ],
    verified: true,
    interests: ['Médecine', 'Lecture', 'Natation', 'Bénévolat'],
    distance: 1500,
    online: false,
    lastSeen: '2024-12-20T14:30:00Z',
  },
  {
    id: 'profile-3',
    userId: 'user-3',
    name: 'Benjamin Nsamba',
    age: 30,
    gender: 'homme',
    city: 'Kinshasa',
    profession: 'Entrepreneur',
    religion: 'Chrétien',
    bio: 'Fondateur d\'une startup tech à Kinshasa. Ambitieux mais grounded. Je valorise la famille et la foi.',
    photoUrl: AVATAR(75),
    photoGallery: [
      AVATAR(75),
      AVATAR(76),
    ],
    verified: true,
    interests: ['Business', 'Tech', 'Football', 'Cuisine'],
    distance: 5,
    online: true,
    lastSeen: new Date().toISOString(),
  },
  {
    id: 'profile-4',
    userId: 'user-4',
    name: 'Esther Tshibangu',
    age: 22,
    gender: 'femme',
    city: 'Goma',
    profession: 'Étudiante en Droit',
    religion: 'Chrétienne',
    bio: 'Future avocate, je défends ce en quoi je crois. Cherche un homme ambitieux et respectueux.',
    photoUrl: AVATAR(17, 'women'),
    photoGallery: [
      AVATAR(17, 'women'),
      AVATAR(18, 'women'),
    ],
    verified: false,
    interests: ['Droit', 'Débat', 'Lecture', 'Musique'],
    distance: 2000,
    online: false,
    lastSeen: '2024-12-19T09:00:00Z',
  },
  {
    id: 'profile-5',
    userId: 'user-5',
    name: 'Joel Mwamba',
    age: 27,
    gender: 'homme',
    city: 'Kinshasa',
    profession: 'Photographe',
    religion: 'Chrétien',
    bio: 'Je capture les moments les plus beaux de la vie. À la recherche de quelqu\'un avec qui créer de bons souvenirs.',
    photoUrl: AVATAR(51),
    photoGallery: [
      AVATAR(51),
      AVATAR(52),
    ],
    verified: true,
    interests: ['Photographie', 'Art', 'Nature', 'Voyage'],
    distance: 8,
    online: true,
    lastSeen: new Date().toISOString(),
  },
  {
    id: 'profile-6',
    userId: 'user-6',
    name: 'Naomie Kapinga',
    age: 25,
    gender: 'femme',
    city: 'Kinshasa',
    profession: 'Journaliste',
    religion: 'Chrétienne',
    bio: 'Journaliste freelance, je suis curieuse de nature et j\'adore découvrir de nouvelles cultures.',
    photoUrl: AVATAR(25, 'women'),
    photoGallery: [
      AVATAR(25, 'women'),
      AVATAR(26, 'women'),
    ],
    verified: true,
    interests: ['Écriture', 'Voyage', 'Politique', 'Café'],
    distance: 2,
    online: false,
    lastSeen: '2024-12-21T18:45:00Z',
  },
  {
    id: 'profile-7',
    userId: 'user-7',
    name: 'David Kalala',
    age: 32,
    gender: 'homme',
    city: 'Lubumbashi',
    profession: 'Comptable',
    religion: 'Musulman',
    bio: 'Père de famille moderne, je cherche une relation stable et épanouissante. Sérieux et attentionné.',
    photoUrl: AVATAR(22),
    photoGallery: [
      AVATAR(22),
      AVATAR(23),
    ],
    verified: true,
    interests: ['Finance', 'Football', 'Cuisine', 'Famille'],
    distance: 1500,
    online: true,
    lastSeen: new Date().toISOString(),
  },
  {
    id: 'profile-8',
    userId: 'user-8',
    name: 'Christelle Mbala',
    age: 23,
    gender: 'femme',
    city: 'Kinshasa',
    profession: 'Styliste',
    religion: 'Chrétienne',
    bio: 'Créatrice de mode, je transforme les tissus en art. Cherche l\'âme sœur qui apprecie la beauté dans les petites choses.',
    photoUrl: AVATAR(38, 'women'),
    photoGallery: [
      AVATAR(38, 'women'),
      AVATAR(39, 'women'),
    ],
    verified: false,
    interests: ['Mode', 'Design', 'Danse', 'Shopping'],
    distance: 4,
    online: true,
    lastSeen: new Date().toISOString(),
  },
  {
    id: 'profile-9',
    userId: 'user-9',
    name: 'Hervé Ilunga',
    age: 29,
    gender: 'homme',
    city: 'Goma',
    profession: 'Professeur',
    religion: 'Chrétien',
    bio: 'Enseignant d\'anglais, je croix en l\'éducation comme outil de changement. Homme de principes et de valeurs.',
    photoUrl: AVATAR(55),
    photoGallery: [
      AVATAR(55),
      AVATAR(56),
    ],
    verified: true,
    interests: ['Éducation', 'Langues', 'Lecture', 'Randonnée'],
    distance: 2000,
    online: false,
    lastSeen: '2024-12-20T11:00:00Z',
  },
  {
    id: 'profile-10',
    userId: 'user-10',
    name: 'Ruth Nyota',
    age: 26,
    gender: 'femme',
    city: 'Kinshasa',
    profession: 'Chanteuse',
    religion: 'Chrétienne',
    bio: 'Gospel singer et compositrice. La musique est ma passion, mais l\'amour est ma priorité. 🎵',
    photoUrl: AVATAR(55, 'women'),
    photoGallery: [
      AVATAR(55, 'women'),
      AVATAR(56, 'women'),
    ],
    verified: true,
    interests: ['Musique', 'Église', 'Chant', 'Piano'],
    distance: 6,
    online: true,
    lastSeen: new Date().toISOString(),
  },
  {
    id: 'profile-11',
    userId: 'user-11',
    name: 'Emmanuel Kashala',
    age: 35,
    gender: 'homme',
    city: 'Kinshasa',
    profession: 'Avocat',
    religion: 'Chrétien',
    bio: 'Avocat au barreau de Kinshasa. La justice et la famille sont mes valeurs fondamentales.',
    photoUrl: AVATAR(60),
    photoGallery: [
      AVATAR(60),
      AVATAR(61),
    ],
    verified: true,
    interests: ['Droit', 'Politique', 'Lecture', 'Golf'],
    distance: 10,
    online: false,
    lastSeen: '2024-12-21T20:00:00Z',
  },
  {
    id: 'profile-12',
    userId: 'user-12',
    name: 'Samantha Ilunga',
    age: 21,
    gender: 'femme',
    city: 'Mbuji-Mayi',
    profession: 'Étudiante en Informatique',
    religion: 'Chrétienne',
    bio: 'Future développeuse full-stack. Passionnée par l\'innovation technologique et les chats 🐱',
    photoUrl: AVATAR(5, 'women'),
    photoGallery: [
      AVATAR(5, 'women'),
      AVATAR(6, 'women'),
    ],
    verified: false,
    interests: ['Programmation', 'Jeux vidéo', 'Café', 'Cinéma'],
    distance: 800,
    online: true,
    lastSeen: new Date().toISOString(),
  },
  {
    id: 'profile-13',
    userId: 'user-13',
    name: 'Fabrice Mulumba',
    age: 26,
    gender: 'homme',
    city: 'Kinshasa',
    profession: 'Chef Cuisinier',
    religion: 'Musulman',
    bio: 'Chef dans un restaurant 5 étoiles. La cuisine est mon art, et je cherche quelqu\'un à qui cuisiner pour la vie.',
    photoUrl: AVATAR(84),
    photoGallery: [
      AVATAR(84),
      AVATAR(85),
    ],
    verified: true,
    interests: ['Cuisine', 'Voyage', 'Musique', 'Photographie'],
    distance: 3,
    online: true,
    lastSeen: new Date().toISOString(),
  },
  {
    id: 'profile-14',
    userId: 'user-14',
    name: 'Patience Lushima',
    age: 28,
    gender: 'femme',
    city: 'Kinshasa',
    profession: 'Pharmacienne',
    religion: 'Chrétienne',
    bio: 'Pharmacienne diplômée, je prends soin de la santé des autres. Il est temps de prendre soin de mon cœur. 💊❤️',
    photoUrl: AVATAR(33, 'women'),
    photoGallery: [
      AVATAR(33, 'women'),
      AVATAR(34, 'women'),
    ],
    verified: true,
    interests: ['Santé', 'Yoga', 'Lecture', 'Nature'],
    distance: 7,
    online: false,
    lastSeen: '2024-12-21T16:30:00Z',
  },
  {
    id: 'profile-15',
    userId: 'user-15',
    name: 'Glody Mpiana',
    age: 31,
    gender: 'homme',
    city: 'Lubumbashi',
    profession: 'Musicien',
    religion: 'Chrétien',
    bio: 'Guitariste et chanteur. La musique rapproche les cœurs. Cherche une mélodie pour ma vie.',
    photoUrl: AVATAR(41),
    photoGallery: [
      AVATAR(41),
      AVATAR(42),
    ],
    verified: false,
    interests: ['Musique', 'Guitare', 'Danse', 'Voyage'],
    distance: 1500,
    online: true,
    lastSeen: new Date().toISOString(),
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-1',
    matchId: 'match-1',
    participant: MOCK_PROFILES[0],
    messages: [
      { id: 'msg-1', senderId: 'user-1', receiverId: 'user-me', content: 'Bonjour Grace ! Comment vas-tu aujourd\'hui ? 😊', type: 'text', read: true, timestamp: '2024-12-21T10:00:00Z' },
      { id: 'msg-2', senderId: 'user-me', receiverId: 'user-1', content: 'Salut Patrick ! Je vais très bien merci. Et toi ?', type: 'text', read: true, timestamp: '2024-12-21T10:05:00Z' },
      { id: 'msg-3', senderId: 'user-1', receiverId: 'user-me', content: 'Très bien aussi ! Tu as un profil intéressant. Qu\'est-ce que tu fais dans la vie ?', type: 'text', read: true, timestamp: '2024-12-21T10:10:00Z' },
      { id: 'msg-4', senderId: 'user-me', receiverId: 'user-1', content: 'Je suis développeuse web. J\'adore créer des applications et des sites internet !', type: 'text', read: true, timestamp: '2024-12-21T10:15:00Z' },
      { id: 'msg-5', senderId: 'user-1', receiverId: 'user-me', content: 'Ah super ! On a quelque chose en commun alors. Le monde de la tech est fascinant !', type: 'text', read: false, timestamp: '2024-12-21T10:20:00Z' },
    ],
    lastMessage: 'Ah super ! On a quelque chose en commun alors. Le monde de la tech est fascinant !',
    lastMessageTime: '10:20',
    unreadCount: 1,
    online: true,
    lastSeen: new Date().toISOString(),
  },
  {
    id: 'conv-2',
    matchId: 'match-2',
    participant: MOCK_PROFILES[2],
    messages: [
      { id: 'msg-6', senderId: 'user-3', receiverId: 'user-me', content: 'Hey ! J\'ai vu qu\'on aime tous les deux la cuisine. Tu es Kinshasienne ?', type: 'text', read: true, timestamp: '2024-12-20T15:00:00Z' },
      { id: 'msg-7', senderId: 'user-me', receiverId: 'user-3', content: 'Oui ! Originaire de Kinshasa. Tu connais un bon restaurant dans la ville ?', type: 'text', read: true, timestamp: '2024-12-20T15:30:00Z' },
      { id: 'msg-8', senderId: 'user-3', receiverId: 'user-me', content: 'Bien sûr ! Je connais un endroit incroyable à Gombe. On pourrait y aller ensemble un de ces jours 😄', type: 'text', read: true, timestamp: '2024-12-20T16:00:00Z' },
    ],
    lastMessage: 'Bien sûr ! Je connais un endroit incroyable à Gombe. On pourrait y aller ensemble un de ces jours 😄',
    lastMessageTime: 'Hier',
    unreadCount: 0,
    online: true,
    lastSeen: new Date().toISOString(),
  },
  {
    id: 'conv-3',
    matchId: 'match-3',
    participant: MOCK_PROFILES[4],
    messages: [
      { id: 'msg-9', senderId: 'user-5', receiverId: 'user-me', content: 'Salut Grace, j\'adore ta galerie photo ! Tu aimes la photographie ?', type: 'text', read: true, timestamp: '2024-12-19T12:00:00Z' },
      { id: 'msg-10', senderId: 'user-me', receiverId: 'user-5', content: 'Merci Joel ! Oui j\'aime beaucoup prendre des photos surtout en voyage.', type: 'text', read: true, timestamp: '2024-12-19T12:30:00Z' },
    ],
    lastMessage: 'Merci Joel ! Oui j\'aime beaucoup prendre des photos surtout en voyage.',
    lastMessageTime: 'Hier',
    unreadCount: 0,
    online: true,
    lastSeen: new Date().toISOString(),
  },
  {
    id: 'conv-4',
    matchId: 'match-4',
    participant: MOCK_PROFILES[9],
    messages: [
      { id: 'msg-11', senderId: 'user-10', receiverId: 'user-me', content: 'Hello Grace ! 🎵 Tu aimes la musique gospel ?', type: 'text', read: false, timestamp: '2024-12-21T08:00:00Z' },
      { id: 'msg-12', senderId: 'user-10', receiverId: 'user-me', content: 'Je chante à l\'église chaque dimanche. Peut-être qu\'on se croise un jour !', type: 'text', read: false, timestamp: '2024-12-21T08:05:00Z' },
      { id: 'msg-13', senderId: 'user-10', receiverId: 'user-me', content: 'Tu es chrétienne aussi non ? ❤️', type: 'text', read: false, timestamp: '2024-12-21T08:10:00Z' },
    ],
    lastMessage: 'Tu es chrétienne aussi non ? ❤️',
    lastMessageTime: '08:10',
    unreadCount: 3,
    online: true,
    lastSeen: new Date().toISOString(),
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: 'post-1',
    authorId: 'user-1',
    authorName: 'Patrick Lumumba',
    authorPhoto: AVATAR(32),
    content: 'Premier jour sur Kinzola ! Je cherche une relation sérieuse et durable. Si tu es quelqu\'un de passionné et ambitieux, n\'hésite pas à me contacter. 🙏',
    imageUrl: 'https://picsum.photos/seed/drc1/1200/800',
    views: 234,
    likes: 45,
    liked: false,
    comments: [
      { id: 'c1', authorId: 'user-3', authorName: 'Benjamin Nsamba', authorPhoto: AVATAR(75), content: 'Bienvenue Patrick ! 🎉', createdAt: '2024-12-21T11:00:00Z' },
      { id: 'c2', authorId: 'user-5', authorName: 'Joel Mwamba', authorPhoto: AVATAR(51), content: 'Bon courage mon frère !', createdAt: '2024-12-21T11:30:00Z' },
    ],
    createdAt: '2024-12-21T10:00:00Z',
    expiresAt: '2024-12-23T10:00:00Z',
    type: 'photo',
    visibility: 'public',
  },
  {
    id: 'post-2',
    authorId: 'user-6',
    authorName: 'Naomie Kapinga',
    authorPhoto: AVATAR(25, 'women'),
    content: 'Un café, un livre, et la paix du matin ☕📚 C\'est les petites choses qui font le bonheur. Quel est votre livre préféré ?',
    views: 156,
    likes: 32,
    liked: true,
    comments: [
      { id: 'c3', authorId: 'user-8', authorName: 'Christelle Mbala', authorPhoto: AVATAR(38, 'women'), content: 'Moi c\'est "Le Petit Prince" ! ❤️', createdAt: '2024-12-21T09:00:00Z' },
    ],
    createdAt: '2024-12-21T08:00:00Z',
    expiresAt: '2024-12-23T08:00:00Z',
    type: 'text',
    visibility: 'public',
  },
  {
    id: 'post-3',
    authorId: 'user-10',
    authorName: 'Ruth Nyota',
    authorPhoto: AVATAR(55),
    content: 'Dimanche de louange extraordinaire à ma paroisse ! 🎵✨ La musique touche toujours mon cœur. Que Dieu vous bénisse tous !',
    imageUrl: 'https://picsum.photos/seed/church1/1200/800',
    views: 312,
    likes: 89,
    liked: false,
    comments: [],
    createdAt: '2024-12-21T12:00:00Z',
    expiresAt: '2024-12-22T12:00:00Z',
    type: 'photo',
    visibility: 'friends',
  },
  {
    id: 'post-4',
    authorId: 'user-13',
    authorName: 'Fabrice Mulumba',
    authorPhoto: AVATAR(84),
    content: 'Nouveau plat créé aujourd\'hui : Poulet moambé réinventé avec une touche moderne ! 🍗✨ La cuisine congolaise a tant à offrir au monde.',
    imageUrl: 'https://picsum.photos/seed/food1/1200/800',
    views: 445,
    likes: 112,
    liked: true,
    comments: [
      { id: 'c4', authorId: 'user-1', authorName: 'Patrick Lumumba', authorPhoto: AVATAR(32), content: 'Ça a l\'air délicieux ! On peut goûter ? 😋', createdAt: '2024-12-21T13:00:00Z' },
      { id: 'c5', authorId: 'user-3', authorName: 'Benjamin Nsamba', authorPhoto: AVATAR(75), content: 'Le moambé c\'est le plat national ! 🔥', createdAt: '2024-12-21T13:15:00Z' },
    ],
    createdAt: '2024-12-21T11:00:00Z',
    expiresAt: '2024-12-22T11:00:00Z',
    type: 'photo',
    visibility: 'public',
  },
  {
    id: 'post-5',
    authorId: 'user-4',
    authorName: 'Esther Tshibangu',
    authorPhoto: AVATAR(17, 'women'),
    content: 'La justice est un droit fondamental. En tant que future avocate, je me bats chaque jour pour que les voix de chacun soient entendues. ⚖️',
    views: 198,
    likes: 67,
    liked: false,
    comments: [
      { id: 'c6', authorId: 'user-11', authorName: 'Emmanuel Kashala', authorPhoto: AVATAR(60), content: 'Tu me rappelles mes débuts au barreau ! Courage !', createdAt: '2024-12-21T14:00:00Z' },
    ],
    createdAt: '2024-12-21T09:30:00Z',
    expiresAt: '2024-12-23T09:30:00Z',
    type: 'text',
    visibility: 'friends',
  },
];

export const MOCK_STORIES: Story[] = [
  {
    id: 'story-1',
    authorId: 'user-1',
    authorName: 'Patrick L.',
    authorPhoto: AVATAR(32),
    imageUrl: 'https://picsum.photos/seed/story1/800/1400',
    content: '',
    views: 89,
    likes: 23,
    comments: [],
    createdAt: '2024-12-21T09:00:00Z',
    expiresAt: '2024-12-22T09:00:00Z',
    type: 'photo',
  },
  {
    id: 'story-2',
    authorId: 'user-10',
    authorName: 'Ruth N.',
    authorPhoto: AVATAR(55),
    content: 'En studio pour un nouveau titre ! 🎤',
    views: 156,
    likes: 45,
    comments: [],
    createdAt: '2024-12-21T11:00:00Z',
    expiresAt: '2024-12-23T11:00:00Z',
    type: 'text',
  },
  {
    id: 'story-3',
    authorId: 'user-13',
    authorName: 'Fabrice M.',
    authorPhoto: AVATAR(84),
    imageUrl: 'https://picsum.photos/seed/story3/800/1400',
    content: '',
    views: 200,
    likes: 67,
    comments: [],
    createdAt: '2024-12-21T07:00:00Z',
    expiresAt: '2024-12-22T07:00:00Z',
    type: 'photo',
  },
  {
    id: 'story-4',
    authorId: 'user-6',
    authorName: 'Naomie K.',
    authorPhoto: AVATAR(25, 'women'),
    content: 'Le lever du soleil sur Kinshasa est magique 🌅',
    views: 134,
    likes: 38,
    comments: [],
    createdAt: '2024-12-21T06:00:00Z',
    expiresAt: '2024-12-23T06:00:00Z',
    type: 'text',
  },
  {
    id: 'story-5',
    authorId: 'user-8',
    authorName: 'Christelle M.',
    authorPhoto: AVATAR(38, 'women'),
    imageUrl: 'https://picsum.photos/seed/story5/800/1400',
    content: '',
    views: 98,
    likes: 29,
    comments: [],
    createdAt: '2024-12-21T08:00:00Z',
    expiresAt: '2024-12-22T08:00:00Z',
    type: 'photo',
  },
];

export const MOCK_MATCHES: Match[] = [
  {
    id: 'match-1',
    user1Id: 'user-me',
    user2Id: 'user-1',
    profile: MOCK_PROFILES[0],
    createdAt: '2024-12-20T10:00:00Z',
    newMatch: false,
  },
  {
    id: 'match-2',
    user1Id: 'user-me',
    user2Id: 'user-3',
    profile: MOCK_PROFILES[2],
    createdAt: '2024-12-20T14:00:00Z',
    newMatch: false,
  },
  {
    id: 'match-3',
    user1Id: 'user-me',
    user2Id: 'user-5',
    profile: MOCK_PROFILES[4],
    createdAt: '2024-12-19T16:00:00Z',
    newMatch: false,
  },
  {
    id: 'match-4',
    user1Id: 'user-me',
    user2Id: 'user-10',
    profile: MOCK_PROFILES[9],
    createdAt: '2024-12-21T08:00:00Z',
    newMatch: true,
  },
  {
    id: 'match-5',
    user1Id: 'user-me',
    user2Id: 'user-12',
    profile: MOCK_PROFILES[11],
    createdAt: '2024-12-21T09:00:00Z',
    newMatch: true,
  },
];

export const MOCK_LIKES_RECEIVED: Profile[] = [
  MOCK_PROFILES[1],  // Divine Kabongo
  MOCK_PROFILES[3],  // Aline Mwamba
  MOCK_PROFILES[5],  // Gloire Mbuyi
  MOCK_PROFILES[6],  // Bienvenu Kashala
  MOCK_PROFILES[7],  // Christelle Mputa
  MOCK_PROFILES[8],  // Naomie Kapinga
  MOCK_PROFILES[9],  // Ruth Nyota
  MOCK_PROFILES[10], // Grâce Mbuyi
  MOCK_PROFILES[11], // Hervé Tshimanga
  MOCK_PROFILES[12], // Sarah Lokwa
  MOCK_PROFILES[13], // Fabrice Mulumba
  MOCK_PROFILES[14], // Cédric Mbeki
  MOCK_PROFILES[0],  // Patrick Lumumba
  MOCK_PROFILES[2],  // Benjamin Nsamba
  MOCK_PROFILES[4],  // Joel Mwamba
  MOCK_PROFILES[1],  // Divine Kabongo (again)
  MOCK_PROFILES[3],  // Aline Mwamba (again)
  MOCK_PROFILES[5],  // Gloire Mbuyi (again)
  MOCK_PROFILES[7],  // Christelle Mputa (again)
  MOCK_PROFILES[9],  // Ruth Nyota (again)
  MOCK_PROFILES[11], // Hervé Tshimanga (again)
  MOCK_PROFILES[0],  // Patrick Lumumba (again)
  MOCK_PROFILES[2],  // Benjamin Nsamba (again)
];

export const MOCK_VISTORS: Profile[] = [
  MOCK_PROFILES[0],  // Patrick Lumumba
  MOCK_PROFILES[1],  // Divine Kabongo
  MOCK_PROFILES[2],  // Benjamin Nsamba
  MOCK_PROFILES[3],  // Aline Mwamba
  MOCK_PROFILES[5],  // Gloire Mbuyi
  MOCK_PROFILES[6],  // Bienvenu Kashala
  MOCK_PROFILES[7],  // Christelle Mputa
  MOCK_PROFILES[8],  // Naomie Kapinga
  MOCK_PROFILES[9],  // Ruth Nyota
  MOCK_PROFILES[10], // Grâce Mbuyi
  MOCK_PROFILES[11], // Hervé Tshimanga
  MOCK_PROFILES[12], // Sarah Lokwa
  MOCK_PROFILES[13], // Fabrice Mulumba
  MOCK_PROFILES[14], // Cédric Mbeki
  MOCK_PROFILES[0],  // Patrick Lumumba (again)
  MOCK_PROFILES[1],  // Divine Kabongo (again)
  MOCK_PROFILES[2],  // Benjamin Nsamba (again)
  MOCK_PROFILES[3],  // Aline Mwamba (again)
  MOCK_PROFILES[4],  // Joel Mwamba
  MOCK_PROFILES[5],  // Gloire Mbuyi (again)
  MOCK_PROFILES[6],  // Bienvenu Kashala (again)
  MOCK_PROFILES[7],  // Christelle Mputa (again)
  MOCK_PROFILES[8],  // Naomie Kapinga (again)
];

export const AVAILABLE_CITIES = [
  'Kinshasa',
  'Lubumbashi',
  'Goma',
  'Mbuji-Mayi',
  'Kananga',
  'Kisangani',
  'Bukavu',
  'Matadi',
];

export const AVAILABLE_RELIGIONS = [
  'Chrétien',
  'Chrétienne',
  'Musulman',
  'Musulmane',
  'Autre',
];

export const AVAILABLE_INTERESTS = [
  'Technologie',
  'Musique',
  'Lecture',
  'Voyage',
  'Cuisine',
  'Sport',
  'Cinéma',
  'Photographie',
  'Art',
  'Danse',
  'Football',
  'Nature',
  'Yoga',
  'Mode',
  'Business',
  'Finance',
  'Médecine',
  'Droit',
  'Éducation',
  'Langues',
  'Écriture',
  'Politique',
  'Bénévolat',
  'Golf',
  'Natation',
  'Randonnée',
  'Jeux vidéo',
  'Café',
  'Design',
  'Shopping',
  'Famille',
  'Église',
  'Chant',
  'Piano',
  'Guitare',
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    type: 'like',
    title: 'Nouveau j\'aime',
    message: 'Patrick Lumumba a aimé votre publication "Premier jour sur Kinzola !"',
    fromUserId: 'user-1',
    fromUserName: 'Patrick Lumumba',
    fromUserPhoto: AVATAR(32),
    read: false,
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    category: 'social',
    priority: 'normal',
  },
  {
    id: 'notif-2',
    type: 'comment_mention',
    title: 'Mention dans un commentaire',
    message: 'Benjamin Nsamba vous a mentionné dans un commentaire : "@Grace Mbuyi tu devrais voir ça !"',
    fromUserId: 'user-3',
    fromUserName: 'Benjamin Nsamba',
    fromUserPhoto: AVATAR(75),
    read: false,
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    category: 'social',
    priority: 'normal',
  },
  {
    id: 'notif-3',
    type: 'badge_obtained',
    title: 'Badge officiel obtenu 🎉',
    message: 'Félicitations ! Votre badge officiel a été approuvé. Votre profil est maintenant vérifié.',
    read: false,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    category: 'system',
    priority: 'high',
  },
  {
    id: 'notif-4',
    type: 'match',
    title: 'Nouveau match !',
    message: 'Vous avez matché avec Ruth Nyota. Commencez une conversation !',
    fromUserId: 'user-10',
    fromUserName: 'Ruth Nyota',
    fromUserPhoto: AVATAR(55),
    read: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    category: 'social',
    priority: 'high',
    actionLabel: 'Écrire',
  },
  {
    id: 'notif-5',
    type: 'profile_view',
    title: 'Profil visité',
    message: 'Naomie Kapinga a visité votre profil. Elle pourrait être intéressée par vous !',
    fromUserId: 'user-6',
    fromUserName: 'Naomie Kapinga',
    fromUserPhoto: AVATAR(25, 'women'),
    read: false,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    category: 'social',
    priority: 'low',
    actionLabel: 'Voir',
  },
  {
    id: 'notif-6',
    type: 'match',
    title: 'Nouveau match !',
    message: 'Vous avez matché avec Joel Mwamba. Envoyez-lui un message !',
    fromUserId: 'user-5',
    fromUserName: 'Joel Mwamba',
    fromUserPhoto: AVATAR(51),
    read: true,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    category: 'social',
    priority: 'high',
    actionLabel: 'Écrire',
  },
  {
    id: 'notif-7',
    type: 'comment_mention',
    title: 'Réponse à votre commentaire',
    message: 'Fabrice Mulumba a répondu à votre commentaire sur sa publication.',
    fromUserId: 'user-13',
    fromUserName: 'Fabrice Mulumba',
    fromUserPhoto: AVATAR(84),
    read: true,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    category: 'social',
    priority: 'normal',
  },
  {
    id: 'notif-8',
    type: 'system',
    title: 'Bienvenue sur Kinzola ! 🎊',
    message: 'Merci de rejoindre notre communauté. Complétez votre profil pour augmenter vos chances de match.',
    read: true,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    category: 'system',
    priority: 'low',
    actionLabel: 'Compléter',
  },
  {
    id: 'notif-9',
    type: 'love_interest',
    title: 'Coup de cœur 💕',
    message: 'Quelqu\'un vous a envoyé un coup de cœur. Découvrez qui c\'est !',
    read: true,
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    category: 'social',
    priority: 'high',
    actionLabel: 'Voir',
  },
  {
    id: 'notif-10',
    type: 'like',
    title: 'Publication populaire 🔥',
    message: 'Votre publication a reçu plus de 10 j\'aime ! Continuez à publier du contenu intéressant.',
    read: true,
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    category: 'social',
    priority: 'normal',
  },
];
